version: '3.3'
services:
   db:
       image: mysql:latest
       command: --default-authentication-plugin=mysql_native_password
       restart: always
       volumes:
           - ./mysql:/var/lib/mysql
       ports:
           - 3307:3306
       environment:
           MYSQL_DATABASE: mydb
           MYSQL_ROOT_PASSWORD: demo1234
   adminer:
       image: adminer
       restart: always
       ports:
           - 8888:8080